services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - ADMINER_DEFAULT_SERVER=db
  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
  node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: npm run watch